* visual studio
** debug
*** debugging CArray
    Problem: only the first element be displayed.

    Method:
    1. Open a watch window. Debug=>Window=>Watch=>Watch 1
    2. suppose CArray var is 'A', then input A.m_pData+1 to see the second element in 'A', in name filed of Watch window.

    ref: https://social.msdn.microsoft.com/Forums/vstudio/en-US/4ff419da-63ee-4e3a-8b52-d6311a38d14c/debugging-carrays?forum=vcgeneral

*** open call stack window
    Debug=>Window=>Call stack
*** change variable value
    https://msdn.microsoft.com/en-us/library/aa6fy2x5.aspx
    In variable windows, Autos, Locals or Watch.
    Double click the value column of a variable row, then input the new value.
*** skip a line: set next statement, CTRL+SHIFT+F10
    Use set next statement function. (CTRL+SHIFT+F10)
    1. set a breakpoint at the start line that should be skiped.
    2. move curser to the next line of the end line, and press CTRL+SHIFT+F10.
    3. then F5.
    https://blogs.msdn.microsoft.com/habibh/2009/07/30/debugging-101-how-to-skip-over-code-in-the-visual-studio-debugger/
*** run to cursor, CTRL+F10
    invisible one-shot breakpoint. Excute upto where your cursor is.
    
https://blogs.msdn.microsoft.com/habibh/2009/07/30/debugging-101-how-to-skip-over-code-in-the-visual-studio-debugger/
    
*** debug more than one projects.
    Right click Solution => property=>multiple startup projects=>Select the project that should be started.

    http://stackoverflow.com/questions/2155930/fixing-the-breakpoint-will-not-currently-be-hit-no-symbols-have-been-loaded-fo

    If not doing so, the the breakpoint can't be added.

    
** editor
*** fold if statement block
    Tools=>Option=>Text Editor=>C/C++=>Formating=>Outlining=>Outline Statement Blocks, set to true.

    Right click, select Outlining.