* git
** create a git repos on window
   1. make a dir and cd to that dir
   2. git init --bare
      
      This command will make current dir a git repos
   3. *add permisions*
      #+begin_src sh
      git config core.sharedRepository 0777
      chmod a+w -R .
      #+end_src
      Otherwise other people may can't push to this repos.
** config
   use ~--global~ option to set for global.

$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
*** ignore file mode
    #+begin_src sh
    git config core.fileMode false
    #+end_src

    Or just edit the .git/config file, modify fileMode to false under [core] block(add the line if not exists)
    #+begin_src gitconfig
    [core]
        filemode = false
    #+end_src
*** ignore end of line
    git config core.autocrlf true

    http://stackoverflow.com/questions/20496084/git-status-ignore-line-endings-identical-files-windows-linux-environment

** reset, 回退
   git reset --mixed COMMIT_HASH： 回退到COMMIT_HASH, 不删除文件。
   git reset --hard COMMIT_HASH： 回退到COMMIT_HASH, 删除文件改动。
   
  
** amend last commit
   just add '--amend' to git commit command.
** diff
*** ignore whitespace
    git diff -w

*** show/highlight words difference in different color/format
    git diff --word-diff=color 
    red: deleted words
    green: added words

    A word is a sequence seperated by whitespace.
