* 五笔输入法 
  基于wubi.el的改进。
  1. 通过[[aspk-selectlist.el][select list]]显示待选词。
     
     当前选择高亮。
     
     键绑定：C-f选择下一个，C-b选择前一个，数字直接选择，空格上屏，回车输入当前的输入的英文字母。
     select list通过overlay 实现。
  2. 中英文混输
     
     中文输入情况下，按下键z，进入英文输入状态（此时minibuer提示En mode）。按回车键返回中文输入状态。
** 安装
   先安装wubi.el，然后下载本库的整个elisp目录，并将该目录加入load-path. 最后 (require 'aspk-app-wubi)
** BUG & TODO
*** 在有ovelay的区域上再显示，会没有高亮。
*** 支持联想功能。
*** 文件最后一个字符会被显示在select list的最后面。
*** select list 显示的长度不对。 比实际的要短1-4个字符。 tooltip的BUG。
    root cause: 汉字并不是严格地显示为两个长度。
    ........
    aaaaaaaa
    AAAAAAAA
    哈哈哈哈
    
    可以看出最后的“哈哈哈哈”只显示出了7个字符宽度。FUCK！
    
*** FIXED 目前的运行效率是个问题，效率有点低。
    160428更新，问题根本原因。
    感觉五笔输入法的显示速度确实要快一些了。现在非常快完全达到了要求。
    看来主要原因是重复地创建也删除overlay，导致move-to-window-line变慢了。
    
    之前的笔记：
    如果打字快一点，候选框就弹不出来。
    为什么效率这么低？什么原因呢。因为编写时根本没有考虑效率。
    我觉得主要问题在于tooltip每次显示都要重新计算所有需要显示的东西，所以才这么卡。但我不想修改。
    
    可以通过]
    可以通过profiler-start 来测试效率。然后调用profiler-report显示结果。
    The profiler report show that below function count for many 22%'s cpu time!!!
                    - aspk/window-position-to-buffer-point               2164  22%
                      
    直接返回结果，再分析下结果中没有一个是这样的的哈哈。确实快多了。没有从来没有一个可以这样哈哈。没有一个这是这样。哈哈 
    分析显示 move-to-window-line 是最消耗CPU时间的。所以只要尽可能地少调用这个函数，则速度就会起来。没有一点问题。
    
    还有一个思路：就是总是显示提示框在同一位置。这样便可解决效率问题。就像现在这样哈哈。
    或者显示在当前输入的上一行。这样也可以。
    