* types
  
** common
   int is always 32 bit, short is 16 bit, long is 64 bit.
** char and byte
   byte is the same as char in C, it is a 8 bit integer.
   char is a unicode character, commonly 16 bits.

   The official definition:
   char: The char data type is a single 16-bit Unicode character. It has a minimum value of '\u0000' (or 0) and a maximum value of '\uffff' (or 65,535 inclusive).

   byte: The byte data type is an 8-bit signed two's complement integer. It has a minimum value of -128 and a maximum value of 127 (inclusive). The byte data type can be useful for saving memory in large arrays, where the memory savings actually matters. They can also be used in place of int where their limits help to clarify your code; the fact that a variable's range is limited can serve as a form of documentation.

   Default value of char is  	'\u0000'

   ref: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

   convert string to char:
   https://www.javacodegeeks.com/2010/11/java-best-practices-char-to-byte-and.html
   convert a string to char array: str.toCharArray, then convert each char to two byte.